export interface MigrationDefinition {
  version: number;
  description: string;
  statements: string[];
}

export const MIGRATIONS: MigrationDefinition[] = [
  {
    version: 1,
    description: "Initial MasterCrafter campaign schema",
    statements: [
      `CREATE TABLE IF NOT EXISTS workspace_meta (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS entity_type_definitions (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        type_key TEXT NOT NULL,
        display_name TEXT NOT NULL,
        icon TEXT NOT NULL,
        color TEXT NOT NULL,
        description TEXT NOT NULL,
        builtin INTEGER NOT NULL DEFAULT 0,
        field_definitions_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, type_key)
      )`,
      `CREATE TABLE IF NOT EXISTS entities (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        type_key TEXT NOT NULL,
        title TEXT NOT NULL,
        subtitle TEXT NOT NULL,
        description TEXT NOT NULL,
        markdown TEXT NOT NULL,
        image_asset_id TEXT,
        tags_json TEXT NOT NULL,
        linked_map_id TEXT,
        linked_placement_id TEXT,
        questline_id TEXT,
        family_tree_root_id TEXT,
        custom_fields_json TEXT NOT NULL,
        npc_statblock_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS maps (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        asset_id TEXT NOT NULL,
        asset_name TEXT NOT NULL,
        asset_path TEXT NOT NULL,
        width INTEGER NOT NULL,
        height INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS map_placements (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        map_id TEXT NOT NULL,
        entity_id TEXT,
        label TEXT NOT NULL,
        kind TEXT NOT NULL,
        geometry_json TEXT NOT NULL,
        text_width INTEGER NOT NULL DEFAULT 48,
        text_height INTEGER NOT NULL DEFAULT 48,
        text_offset_x REAL NOT NULL DEFAULT 0,
        text_offset_y REAL NOT NULL DEFAULT 0,
        notes TEXT NOT NULL,
        color TEXT NOT NULL,
        glow_color TEXT NOT NULL DEFAULT '#77c8ff',
        shadow_color TEXT NOT NULL DEFAULT '#000000',
        z_index INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(map_id) REFERENCES maps(id) ON DELETE CASCADE,
        FOREIGN KEY(entity_id) REFERENCES entities(id) ON DELETE SET NULL
      )`,
      `CREATE TABLE IF NOT EXISTS notes (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        title TEXT NOT NULL,
        slug TEXT NOT NULL,
        kind TEXT NOT NULL,
        body TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        linked_entity_ids_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, slug)
      )`,
      `CREATE TABLE IF NOT EXISTS content_links (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        target_key TEXT NOT NULL,
        target_type TEXT NOT NULL,
        target_id TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS questlines (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        anchor_entity_id TEXT,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        status TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS quest_nodes (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        questline_id TEXT NOT NULL,
        parent_node_id TEXT,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        rewards_json TEXT NOT NULL,
        order_index INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(questline_id) REFERENCES questlines(id) ON DELETE CASCADE,
        FOREIGN KEY(parent_node_id) REFERENCES quest_nodes(id) ON DELETE SET NULL
      )`,
      `CREATE TABLE IF NOT EXISTS timeline_events (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        entity_id TEXT,
        quest_node_id TEXT,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        event_type TEXT NOT NULL,
        lane_kind TEXT NOT NULL,
        lane_label TEXT NOT NULL,
        stamp_json TEXT NOT NULL,
        duration_minutes INTEGER NOT NULL,
        location_entity_id TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS relations (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        source_entity_id TEXT NOT NULL,
        target_entity_id TEXT NOT NULL,
        relation_kind TEXT NOT NULL,
        label TEXT NOT NULL,
        notes TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS items (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        worth INTEGER NOT NULL,
        rarity TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS store_stocks (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        store_entity_id TEXT NOT NULL,
        item_id TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        price_override INTEGER,
        notes TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, store_entity_id, item_id)
      )`,
      `CREATE TABLE IF NOT EXISTS assets (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        original_name TEXT NOT NULL,
        file_name TEXT NOT NULL,
        relative_path TEXT NOT NULL,
        absolute_path TEXT NOT NULL,
        mime_type TEXT NOT NULL,
        size_bytes INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, relative_path)
      )`,
      `CREATE VIRTUAL TABLE IF NOT EXISTS search_index_fts USING fts5(
        workspace_id UNINDEXED,
        record_type UNINDEXED,
        record_id UNINDEXED,
        type_key UNINDEXED,
        title,
        body,
        tags,
        tokenize = 'unicode61'
      )`,
      `CREATE INDEX IF NOT EXISTS idx_entities_workspace_type ON entities(workspace_id, type_key)`,
      `CREATE INDEX IF NOT EXISTS idx_maps_workspace ON maps(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_map_placements_map ON map_placements(map_id)`,
      `CREATE INDEX IF NOT EXISTS idx_notes_workspace ON notes(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_content_links_workspace_target ON content_links(workspace_id, target_key)`,
      `CREATE INDEX IF NOT EXISTS idx_questlines_workspace ON questlines(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_quest_nodes_questline ON quest_nodes(questline_id)`,
      `CREATE INDEX IF NOT EXISTS idx_timeline_workspace ON timeline_events(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_relations_workspace ON relations(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_items_workspace ON items(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_store_stocks_workspace ON store_stocks(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_assets_workspace ON assets(workspace_id)`,
    ],
  },
  {
    version: 2,
    description: "Add entity slugs for backlinks and search targeting",
    statements: [
      `ALTER TABLE entities ADD COLUMN slug TEXT NOT NULL DEFAULT ''`,
      `UPDATE entities
       SET slug = lower(replace(replace(replace(trim(title), ' ', '-'), '/', '-'), '\\', '-')) || '-' || substr(id, 1, 8)
       WHERE slug = ''`,
      `CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_workspace_slug ON entities(workspace_id, slug)`,
    ],
  },
  {
    version: 3,
    description: "Add marker scale and font color",
    statements: [
      `ALTER TABLE map_placements ADD COLUMN scale REAL NOT NULL DEFAULT 1`,
      `ALTER TABLE map_placements ADD COLUMN font_color TEXT NOT NULL DEFAULT '#ffffff'`,
    ],
  },
  {
    version: 4,
    description: "Persist quest node calendar stamps",
    statements: [
      `ALTER TABLE quest_nodes ADD COLUMN stamp_json TEXT`,
    ],
  },
  {
    version: 5,
    description: "Add placement glow and shadow colors",
    statements: [
      `ALTER TABLE map_placements ADD COLUMN glow_color TEXT NOT NULL DEFAULT '#77c8ff'`,
      `ALTER TABLE map_placements ADD COLUMN shadow_color TEXT NOT NULL DEFAULT '#000000'`,
    ],
  },
  {
    version: 6,
    description: "Add separate placement text dimensions",
    statements: [
      `ALTER TABLE map_placements ADD COLUMN text_width INTEGER NOT NULL DEFAULT 48`,
      `ALTER TABLE map_placements ADD COLUMN text_height INTEGER NOT NULL DEFAULT 48`,
    ],
  },
  {
    version: 7,
    description: "Add placement text offsets",
    statements: [
      `ALTER TABLE map_placements ADD COLUMN text_offset_x REAL NOT NULL DEFAULT 0`,
      `ALTER TABLE map_placements ADD COLUMN text_offset_y REAL NOT NULL DEFAULT 0`,
    ],
  },
  {
    version: 8,
    description: "Add optional NPC statblocks",
    statements: [
      `ALTER TABLE entities ADD COLUMN npc_statblock_json TEXT`,
    ],
  },
  {
    version: 9,
    description: "Add encounter, NPC library, and player library tables",
    statements: [
      `CREATE TABLE IF NOT EXISTS encounters (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        name TEXT NOT NULL,
        slug TEXT NOT NULL,
        description TEXT NOT NULL,
        notes TEXT NOT NULL,
        map_id TEXT,
        tags_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, slug)
      )`,
      `CREATE TABLE IF NOT EXISTS encounter_combatants (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        encounter_id TEXT NOT NULL,
        source_kind TEXT NOT NULL,
        source_id TEXT,
        team TEXT NOT NULL,
        name TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        initiative_bonus INTEGER NOT NULL,
        armor_class INTEGER NOT NULL,
        hit_points INTEGER NOT NULL,
        speed TEXT NOT NULL,
        level INTEGER,
        challenge_rating TEXT NOT NULL,
        notes TEXT NOT NULL,
        sort_index INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(encounter_id) REFERENCES encounters(id) ON DELETE CASCADE
      )`,
      `CREATE TABLE IF NOT EXISTS encounter_sessions (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        encounter_id TEXT NOT NULL,
        status TEXT NOT NULL,
        round_number INTEGER NOT NULL,
        current_turn_index INTEGER NOT NULL,
        started_at TEXT NOT NULL,
        last_advanced_at TEXT NOT NULL,
        ended_at TEXT,
        state_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY(encounter_id) REFERENCES encounters(id) ON DELETE CASCADE
      )`,
      `CREATE TABLE IF NOT EXISTS npc_library_entries (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        source_entity_id TEXT,
        team TEXT NOT NULL,
        name TEXT NOT NULL,
        slug TEXT NOT NULL,
        challenge_rating TEXT NOT NULL,
        armor_class INTEGER NOT NULL,
        hit_points INTEGER NOT NULL,
        speed TEXT NOT NULL,
        initiative_bonus INTEGER NOT NULL,
        notes TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, slug)
      )`,
      `CREATE TABLE IF NOT EXISTS player_library_entries (
        id TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL,
        name TEXT NOT NULL,
        slug TEXT NOT NULL,
        level INTEGER NOT NULL,
        armor_class INTEGER NOT NULL,
        hit_points INTEGER NOT NULL,
        initiative_bonus INTEGER NOT NULL,
        speed TEXT NOT NULL,
        notes TEXT NOT NULL,
        tags_json TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(workspace_id, slug)
      )`,
      `CREATE INDEX IF NOT EXISTS idx_encounters_workspace ON encounters(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_encounter_combatants_encounter ON encounter_combatants(encounter_id)`,
      `CREATE INDEX IF NOT EXISTS idx_encounter_sessions_workspace ON encounter_sessions(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_npc_library_workspace ON npc_library_entries(workspace_id)`,
      `CREATE INDEX IF NOT EXISTS idx_player_library_workspace ON player_library_entries(workspace_id)`,
    ],
  },
  {
    version: 10,
    description: "Add NPC disposition to the encounter library",
    statements: [
      `ALTER TABLE npc_library_entries ADD COLUMN team TEXT NOT NULL DEFAULT 'enemy'`,
    ],
  },
];
